name: virtual_quiz
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
        - assets/morado/1.png
        - assets/morado/2.png
        - assets/morado/3.png
        - assets/morado/4.png
        - assets/morado/5.png
        - assets/morado/6.png
        - assets/morado/7.png
        - assets/morado/8.png
        - assets/morado/9.png
        - assets/morado/10.png
        - assets/morado/11.png
        - assets/morado/12.png
        - assets/morado/13.png
        - assets/morado/14.png
        - assets/morado/15.png
        - assets/morado/s1.png
        - assets/morado/s2.png
        - assets/morado/s3.png
        - assets/morado/s4.png

        - assets/rojo/1.png
        - assets/rojo/2.png
        - assets/rojo/3.png
        - assets/rojo/4.png
        - assets/rojo/5.png
        - assets/rojo/6.png
        - assets/rojo/7.png
        - assets/rojo/8.png
        - assets/rojo/9.png
        - assets/rojo/10.png
        - assets/rojo/11.png
        - assets/rojo/12.png
        - assets/rojo/13.png
        - assets/rojo/14.png
        - assets/rojo/s1.png
        - assets/rojo/s2.png
        - assets/rojo/s3.png
        - assets/rojo/s4.png

        - assets/azul/1.png
        - assets/azul/2.png
        - assets/azul/3.png
        - assets/azul/4.png
        - assets/azul/5.png
        - assets/azul/6.png
        - assets/azul/7.png
        - assets/azul/8.png
        - assets/azul/9.png
        - assets/azul/10.png
        - assets/azul/11.png
        - assets/azul/12.png
        - assets/azul/13.png
        - assets/azul/14.png
        - assets/azul/s1.png
        - assets/azul/s2.png
        - assets/azul/s3.png
        - assets/azul/s4.png

        - assets/naranja/1.png
        - assets/naranja/2.png
        - assets/naranja/3.png
        - assets/naranja/4.png
        - assets/naranja/5.png
        - assets/naranja/6.png
        - assets/naranja/7.png
        - assets/naranja/8.png
        - assets/naranja/9.png
        - assets/naranja/10.png
        - assets/naranja/11.png
        - assets/naranja/12.png
        - assets/naranja/13.png
        - assets/naranja/14.png
        - assets/naranja/15.png
        - assets/naranja/s1.png
        - assets/naranja/s2.png
        - assets/naranja/s3.png
        - assets/naranja/s4.png

        - assets/amarillo/s1.png
        - assets/amarillo/s2.png
        - assets/amarillo/s3.png
        - assets/amarillo/s4.png

        - assets/verde/s1.png
        - assets/verde/s2.png
        - assets/verde/s3.png
        - assets/verde/s4.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
